### ISSUE TITLE
ordering of objects not always consistent between metadata and feature values csv downloads

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#94]
Through looking at my data carefully, I had the suspicion that the ordering of objects in the feature values and metadata csv downloads do not conform. As I mentioned in issue https://github.com/TissueMAPS/TissueMAPS/issues/48 it would be useful to have a global identifier to crosscheck the two tables rather than relying on the ordering of the objects to merge the two tables.

I implemented this feature https://github.com/TissueMAPS/TmServer/pull/7 to add the mapobject_id to both metadata and feature-values files. I then redownloaded my dataset. Indeed it was the case that for some wells the order of objects between the two files is not consistent. Here are two examples: well E02 has the same ordering in both files, well G02 does not. After merging the two files by row, I made a scatterplot of the mapobject_id (metadata file) and the mapobject_id_features (feature-value file).

![unsorted](https://user-images.githubusercontent.com/5407848/32301141-f68fa7ea-bf5c-11e7-93f4-731b2ff85aab.jpg)

Obviously the ordering is correct in E02 and not in G02.

Note that the same objects are contained in both the metadata and feature-values files because if these are sorted before merging, everything is ok.

![sorted](https://user-images.githubusercontent.com/5407848/32301205-3d905b3a-bf5d-11e7-94d2-0f5846a0a750.jpg)

Here's the same thing across my plate:

![plate](https://user-images.githubusercontent.com/5407848/32301369-fba04cb6-bf5d-11e7-98bf-ae070a164931.jpg)

https://github.com/TissueMAPS/TmServer/pull/7 is a start towards fixing this, but ideally the ordering between the two files should be preserved. Moreover, is there a good reason to have two separate files anyway? I would imaging that most users would prefer the metadata and the feature-values as one file.

**Comment by jluethi** [comment]
Wow that's bad!
Do you know how this relates to the label ids saved in the metadata file? Is the mix-up solely in the ordering of the rows of the feature value file or do you see anything suggesting a mix-up between single cell values?

**Comment by jluethi** [comment]
@sparkvilla @riccardomurri This is an important issue! We haven't seen this in our test data, because the data we manually verified (the synthetic test case) was fine. It seems that we got "lucky" (/unlucky) by getting some wells where the ordering was conserved.

**Comment by scottberry** [comment]
@jluethi I think its just the ordering. Here is DAPI/EdU scatter plot showing SVM results either unsorted merge, or sorted merge.

unsorted:
![unsorted_svm](https://user-images.githubusercontent.com/5407848/32302088-2a1c29c2-bf61-11e7-88e7-6ce4da1cfce5.jpg)

sorted:
![sorted_svm](https://user-images.githubusercontent.com/5407848/32302087-288f79ec-bf61-11e7-8dc3-6be9a7f2a451.jpg)

**Comment by jluethi** [comment]
@scottberry Can you plot something like integrated intensity vs. mean intensity*area for some stainings? That would show us whether the values in the feature table are consistent per row or whether it's an even bigger mess...

**Comment by scottberry** [comment]
@jluethi I think the feature table itself is fine, its just comparing across the two tables that is a problem (like SVMs, border cells, etc.)

![within_feature_comparison](https://user-images.githubusercontent.com/5407848/32302247-f784f4e8-bf61-11e7-903f-2c0b7c00b7e2.jpg)

**Comment by jluethi** [comment]
@scottberry Well, that's a beginning. Thx for the quick & data-rich response!
It still remains a big problem though obviously, as any attempt to use SVMs or border cell IDs for data cleanup will not work at all. In my opinion, this is a **critical bug that urgently needs to be addressed.** Any data analysis based on TissueMaps data that uses data cleanup, which is most feature-based data analysis based on TissueMaps data, needs to be considered potentially compromised.

**Comment by hackermd** [comment]
@scottberry thanks for digging into this!

I've just reviewed the server side API view functions: `get_feature_values()` and `get_metadata()` both reuse the same function to build the list of mapobjects (see [here](https://github.com/TissueMAPS/TmServer/blob/d2917a7191a21ec2825b0c7bf879998f7b08f50d/tmserver/api/feature.py#L382) and [here](https://github.com/TissueMAPS/TmServer/blob/d2917a7191a21ec2825b0c7bf879998f7b08f50d/tmserver/api/feature.py#L594), respectively) and this function orders entries in the list by `mapobject_id` (see [here](https://github.com/TissueMAPS/TmServer/blob/d2917a7191a21ec2825b0c7bf879998f7b08f50d/tmserver/api/mapobject.py#L163)). Based on this order, `feature_values` and `label_values` are later retrieved from a dictionary using the `mapobject_id` as a key (see [here](https://github.com/TissueMAPS/TmServer/blob/d2917a7191a21ec2825b0c7bf879998f7b08f50d/tmserver/api/feature.py#L420) and [here](https://github.com/TissueMAPS/TmServer/blob/d2917a7191a21ec2825b0c7bf879998f7b08f50d/tmserver/api/feature.py#L657), respectively). I can't see where the problem lies and would need to do some more digging myself..

Irrespective of the source of the problem, I totally agree that it makes sense to include the `mapobject_id` as a column in both tables in order to be able to join them. I actually added this already in the `feature/multiple-jterator-pipelines` branch (see [here](https://github.com/TissueMAPS/TmServer/blob/feature/multiple-jterator-pipelines/tmserver/api/feature.py#L471)), but this effort is not yet finished and has thus not been merged so far.

> Moreover, is there a good reason to have two separate files anyway?

The main motivation for doing this was to facilitate working with large files that contain many objects and feature values, which would take a lot of time to load into memory. Having two separate files allows loading the *metadata* first to build an index to subsequently only load the relevant subset of rows from the feature values table.

**Comment by jluethi** [comment]
I'll be trying to reproduce this issue on an experiment with 36 wells. Will probably take most of today to run with @scottberry pull request to tmserver (https://github.com/TissueMAPS/TmServer/pull/7), so that I have measurements where the mapobject_id is saved for both feature-values and metadata. I'll report back as soon as I know more.

**Comment by scottberry** [comment]
If you already have features measured, you don’t need to re-run the analysis, just the download.
Scott

**Comment by jluethi** [comment]
I can reproduce this bug on an independent dataset, on an independent VM running TissueMaps v0.3.3. The feature values and metadata are ordered the same for some wells, but not for others. I think it may be site/dependent, because even in the wells where the correlation is messed up, some still lay on the diagonal.

![mapobject_ids](https://user-images.githubusercontent.com/18033446/32321342-175eba38-bfc1-11e7-9ba1-09f2b1064480.png)

**Comment by jluethi** [comment]
I looked into my data at bit more and found one trend: It seems that all odd columns are fine in my data, all even columns are messed up to different degrees. In Scott's data, this didn't seem to happen with the same periodicity, so I don't know what's causing this.

![mapobject_mapping](https://user-images.githubusercontent.com/18033446/32324179-c88c66ee-bfca-11e7-94fd-9da6e4a5ef61.png)

Also, in the wells where there are off-diagonal point (e.g. cells where mapobject id of metadata & feature-values don't correspond to each other), there are also some cells that are fine. I though this might be site-related, but I see no trend in the sites. It seems that some of the cells just happen to be correct (or maybe they're also off but just by a few values, while others are off much more)

![mapobjectids_b02](https://user-images.githubusercontent.com/18033446/32324249-09c55076-bfcb-11e7-9385-5f57ddaaa2cc.png)

**Comment by riccardomurri** [comment]
hi @scottberry and @jluethi -- does the code in Scott's PR work around the problem for now, or is some urgent fix needed?

**Comment by scottberry** [comment]
The PR ok for now, but this sorting issue should be addressed in the next few weeks. I think @jluethi tested that the PR is ok on the most recent version, so it could even be added directly to current master.

**Comment by jluethi** [comment]
Well, the PR doesn't fix the issue. It just gives the user tools to fix it in post. We will have to inform all users using the feature data that they need to do manual sorting until this is fixed.
The faster the underlying problem can be solved, the better!
Concerning testing of the fix: It seems to be working fine on a v0.3.3 release. I haven't run any of the official tests. They would fail, because there is now additional information being downloaded. But I think it's a good idea to expose that additional information (the mapobject id) until we're sure the problem is fixed

**Comment by hackermd** [comment]
Can you please print the `mapobjects` list as well as the `feature_values_lut` and `label_values_lut` dictionaries in the `get_feature_values()` and `get_metadata()` view functions, respectively?

**Comment by hackermd** [comment]
Are we sure this is not a client-side problem?

Can you please try to download feature values and metadata separately via the Python API using the [download_feature_values()](https://github.com/TissueMAPS/TmClient/blob/d261ef7fc8cbb27f41387c072e40840c2f4f3959/src/python/tmclient/api.py#L1888) and [download_object_metadata()](https://github.com/TissueMAPS/TmClient/blob/d261ef7fc8cbb27f41387c072e40840c2f4f3959/src/python/tmclient/api.py#L2019) functions, respectively, instead of using the CLI? The `iter_content()` in the [download_feature_values_and_metadata_files()](https://github.com/TissueMAPS/TmClient/blob/d261ef7fc8cbb27f41387c072e40840c2f4f3959/src/python/tmclient/api.py#L1968) function used by the CLI may screw up the order..

**Comment by scottberry** [comment]
First few rows of the csv files obtained after download.
features:

| mapobject_id | Nuclei_Intensity_max_DAPI.rescaled_image | Nuclei_Intensity_mean_DAPI.rescaled_image | Nuclei_Intensity_min_DAPI.rescaled_image | Nuclei_Intensity_sum_DAPI.rescaled_image | Nuclei_Intensity_std_DAPI.rescaled_image | 
|--------------|------------------------------------------|-------------------------------------------|------------------------------------------|------------------------------------------|------------------------------------------| 
| 406560       | 254                                      | 134.065026                                | 9                                        | 577284                                   | 39.304331                                | 
| 406561       | 279                                      | 127.09603                                 | 10                                       | 963515                                   | 35.485251                                | 
| 406562       | 251                                      | 120.091559                                | 3                                        | 1829715                                  | 35.867362                                | 
| 406563       | 423                                      | 179.245368                                | 9                                        | 793340                                   | 82.584054                                | 
| 406564       | 281                                      | 124.484068                                | 4                                        | 976702                                   | 47.697042                                | 

metadata:

| mapobject_id | plate_name | well_name | well_pos_y | well_pos_x | tpoint | zplane | label | is_border | Sphase | Mphase | Heatmap-115 | 
|--------------|------------|-----------|------------|------------|--------|--------|-------|-----------|--------|--------|-------------| 
| 187261       | plate01    | G02       | 7          | 4          | 0      | 0      | 1     | 1         | 1.0    | 0.0    | nan         | 
| 187262       | plate01    | G02       | 7          | 4          | 0      | 0      | 2     | 1         | 0.0    | 0.0    | nan         | 
| 187263       | plate01    | G02       | 7          | 4          | 0      | 0      | 3     | 1         | 1.0    | 0.0    | nan         | 
| 187264       | plate01    | G02       | 7          | 4          | 0      | 0      | 4     | 1         | 1.0    | 0.0    | nan         | 
| 187265       | plate01    | G02       | 7          | 4          | 0      | 0      | 5     | 1         | 1.0    | 0.0    | nan         |

**Comment by riccardomurri** [comment]
> The iter_content() in the download_feature_values_and_metadata_files() function used by the CLI may screw up the order

Unlikely, unless `requests` is doing some very weird things -- it's streaming data from a server, so it naturally comes ordered...

**Comment by riccardomurri** [comment]
My take on this is that the problem is in `generate_feature_matrix()` within `get_metadata()` (`feature.py`, lines 450--679).

At line 538, we have::

            ref_position_lut = dict()

Later, at line 591, the main loop of the function begins::

        for ref_id in ref_position_lut:

The problem is that `ref_position_lut` is a `dict` object, which is
*not* ordered.  So the order of enumeration does not match the order
keys were added in the loops at lines 538--572.

Can you please try applying this patch and check if it solves the problem?

```diff
diff --git a/tmserver/api/feature.py b/tmserver/api/feature.py
index c7bb9b7..280358c 100644
--- a/tmserver/api/feature.py
+++ b/tmserver/api/feature.py
@@ -16,6 +16,7 @@
 """API view functions for querying :mod:`feature <tmlib.models.feature>`
 resources.
 """
+from collections import OrderdDict
 import csv
 import json
 import logging
@@ -535,7 +536,7 @@ def get_metadata(experiment_id, mapobject_type_id):
             for r in results:
                 layer_lut[r.id] = {'tpoint': r.tpoint, 'zplane': r.zplane}

-            ref_position_lut = dict()
+            ref_position_lut = OrderedDict()
             if ref_type == 'Plate':
                 results = _get_matching_plates(session, plate_name)
                 for r in results:
```

**Comment by hackermd** [comment]
@riccardomurri Thanks for spotting this! This would mean that the order of mapobjects are correct per site, but the order of sites would be incorrect and consequently also the order of mapobjects per well.

**Comment by scottberry** [comment]
@riccardomurri, this seems to be the fix! 

After applying the patch:

feature values:

| mapobject_id | Nuclei_Intensity_max_DAPI.rescaled_image | Nuclei_Intensity_mean_DAPI.rescaled_image | Nuclei_Intensity_min_DAPI.rescaled_image | Nuclei_Intensity_sum_DAPI.rescaled_image | 
|--------------|------------------------------------------|-------------------------------------------|------------------------------------------|------------------------------------------| 
| 406560       | 254                                      | 134.065026                                | 9                                        | 577284                                   | 
| 406561       | 279                                      | 127.09603                                 | 10                                       | 963515                                   | 
| 406562       | 251                                      | 120.091559                                | 3                                        | 1829715                                  | 
| 406563       | 423                                      | 179.245368                                | 9                                        | 793340                                   | 

metadata:

| mapobject_id | plate_name | well_name | well_pos_y | well_pos_x | tpoint | zplane | label | is_border | Sphase | Mphase | Heatmap-115 | 
|--------------|------------|-----------|------------|------------|--------|--------|-------|-----------|--------|--------|-------------| 
| 406560       | plate01    | G02       | 0          | 0          | 0      | 0      | 1     | 1         | 0.0    | 0.0    | nan         | 
| 406561       | plate01    | G02       | 0          | 0          | 0      | 0      | 2     | 1         | 0.0    | 0.0    | nan         | 
| 406562       | plate01    | G02       | 0          | 0          | 0      | 0      | 3     | 0         | 0.0    | 0.0    | nan         | 
| 406563       | plate01    | G02       | 0          | 0          | 0      | 0      | 4     | 1         | 0.0    | 0.0    | nan         | 

and making a plot similar to my first post *without sorting* after downloading the csv files

![rplot](https://user-images.githubusercontent.com/5407848/32391820-c7040eee-c0d3-11e7-96cc-c908ac457e37.jpeg)

I have added the fix to https://github.com/TissueMAPS/TmServer/pull/7 . Since a global object identifier is still a useful sanity check to have in final processed data, I would still recommend merging this pull request.

**Comment by jluethi** [comment]
I also tested @riccardomurri 's fix on my dataset. It solves the issue perfectly! Therefore, I would argue for pulling in #TissueMAPS/TmServer#7 to the master as soon as possible, so that nobody gets screwed by misordered measurements.

![metadata_feature_values_riccardofix](https://user-images.githubusercontent.com/18033446/32449867-fbec14da-c312-11e7-9e84-87561e0a5501.png)
